project:
  type: book
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/"

lang: de
    
book:
  title: "Sammlung und Analyse von Social-Media-Daten mit R"
  author: "Johannes Breuer"
  date: "06-09-2026"
  repo-url: "https://github.com/jobreu/social-media-data-r"
  repo-actions: [edit, issue]
  page-footer:
    left: "Materials created by Johannes Breuer"
    right: "This work is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  sidebar:                       
    logo: images/logo.png
  chapters:
    - index.qmd
    - part: "Grundlagen"
      chapters:
      - 01-installation.qmd
      - 02-rstudio.qmd
      - 03-objects.qmd
      - 04-functions.qmd
      - packages.qmd
      - 05-import-export.qmd
    - part: "Data Wrangling"
      chapters:
      - tidyverse.qmd
      - 06-wrangling-df.qmd
      - 07-wrangling-variables.qmd
    - part: "Daten sammeln"
      chapters:
      - 09-collection-methods.qmd
      - 10-bluesky-collection.qmd
      - 11-tiktok-collection.qmd
      - 12-youtube-collection.qmd
    - part: "Datenanalyse"
      chapters:
      - analysis-methods.qmd
      - preprocessing.qmd
      - descriptive-analysis.qmd
      - sent-dict.qmd
      - topicmodels.qmd
    - part: "Tipps & Tricks"
      chapters:
      - 16-errors.qmd
      - 15-message-warning-error.qmd
      - 14-help.qmd
      - 18-function-lifecycle.qmd
      - 13-comments.qmd
      - names.qmd
      - codebooks.qmd
      - 17-paths.qmd
      - projects.qmd
    - references.qmd

crossref:
  sec-prefix: "Kapitel"
  fig-prefix: "Abbildung"
  tbl-prefix: "Tabelle"

# Citations configuration
bibliography: references.bib
csl: apa.csl

# Output formats and styling
format:
  html:
    theme:
      - cosmo
      - brand
    link-external-newwindow: true
    link-external-icon: true
  pdf:
    documentclass: scrreprt