project:
  type: book
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/"
    
book:
  title: "Collecting and Analyzing Social Media Data with R"
  author: "Johannes Breuer"
  date: "21.05.2026"
  sidebar:                       
    logo: images/logo.png
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
      - intro.qmd
    - part: "Data Wrangling"
      chapters:
      - 04-text-data.qmd
    - part: "End"
      chapters:
      - summary.qmd
      - references.qmd

# Citations configuration
bibliography: references.bib

# Output formats and styling
format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt