project:
  type: book
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/"

engine: knitr
    
book:
  title: "Sammlung und Analyse von Social-Media-Daten mit R"
  author: "Johannes Breuer"
  date: "05-21-2026"
  sidebar:                       
    logo: images/logo.png
  chapters:
    - index.qmd
    - part: "Grundlagen"
      chapters:
      - 01-installation.qmd
      - 02-rstudio.qmd
      - 03-objects.qmd
      - 05-import-export.qmd
    - part: "Data Wrangling"
      chapters:
      - 08-text-data.qmd
    - part: "Tipps & Tricks"
      chapters:
      - 13-comments.qmd
      - 14-help.qmd
      - 15-message-warning-error.qmd
      - 16-errors.qmd
      - 17-paths.qmd
      - names.qmd
      - 18-function-lifecycle.qmd
    - references.qmd

# Citations configuration
bibliography: references.bib
csl: apa.csl

# Output formats and styling
format:
  html:
    theme:
      - cosmo
      - brand
    link-external-newwindow: true
    link-external-icon: true
  pdf:
    documentclass: scrreprt