project:
  type: website
  output-dir: ../docs/slides

bibliography: ../references.bib
csl: ../apa.csl

execute:
  echo: true

format:
  revealjs:
    theme: [default, custom.scss]
    slide-number: true
    logo: ../images/logo.png