project:
  type: website
  output-dir: ../docs/slides # Pushes the rendered slides into the book's output folder

format:
  revealjs:
    theme: [default, custom.scss]
    slide-number: true
    logo: ../images/logo.png